"use client";
import { useState, useEffect } from "react";
import Sidebar from "@/components/Sidebar";
import Timeline from "@/components/Timeline";
import DetailPanel from "@/components/DetailPanel";
import DiffViewer from "@/components/DiffViewer";
import { PROJECTS, type Snapshot } from "@/lib/data";

// Wails bindings (auto-generated by Wails CLI at build/dev time)
import { ListSnapshots, RestoreSnapshot, GetProjectName, IsInitialized, InitializeProject, SaveSnapshot } from "@/lib/wailsjs/go/main/WailsApp";

export default function Home() {
  const [snapshots, setSnapshots] = useState<Snapshot[]>([]);
  const [selectedSnapshot, setSelectedSnapshot] = useState<Snapshot | null>(null);
  const [loading, setLoading] = useState(true);
  const [diffFrom, setDiffFrom] = useState<Snapshot | null>(null);
  const [diffTo, setDiffTo] = useState<Snapshot | null>(null);
  const [activeProjectName, setActiveProjectName] = useState("eko");
  const [initialized, setInitialized] = useState(true);

  const activeProjectId = "eko";

  const loadSnapshots = async () => {
    try {
      if (typeof window !== "undefined" && (window as any).go) {
        const isInit = await IsInitialized();
        setInitialized(isInit);

        if (!isInit) {
          const projName = await GetProjectName().catch(() => "eko");
          setActiveProjectName(projName);
          setLoading(false);
          return;
        }

        const [data, projName] = await Promise.all([
          ListSnapshots().catch(() => []),
          GetProjectName().catch(() => "eko")
        ]);
        setSnapshots(data);
        setActiveProjectName(projName);
        if (data.length > 0) {
          setSelectedSnapshot(data[0]);
        } else {
          setSelectedSnapshot(null);
        }
      } else {
        // Fallback to mock data in browser dev mode
        setInitialized(true);
        const mockSnapshots = PROJECTS[0].snapshots;
        setSnapshots(mockSnapshots);
        setActiveProjectName(PROJECTS[0].name);
        if (mockSnapshots.length > 0) {
          setSelectedSnapshot(mockSnapshots[0]);
        }
      }
    } catch (err) {
      console.error("Failed to load snapshots:", err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    loadSnapshots();
  }, []);

  const handleRestore = async (s: Snapshot) => {
    const confirm = window.confirm(`Restore snapshot #${s.id} — "${s.prompt}"?\nThis will revert files in your project directory.`);
    if (!confirm) return;

    try {
      if (typeof window !== "undefined" && (window as any).go) {
        await RestoreSnapshot(s.id);
        alert(`Snapshot #${s.id} restored successfully.`);
      } else {
        alert(`Demo mode: Restore simulated for snapshot #${s.id}`);
      }
    } catch (err: any) {
      alert(`Failed to restore snapshot: ${err.message || err}`);
    }
  };

  const handleDiff = (s: Snapshot) => {
    const idx = snapshots.findIndex((snap) => snap.id === s.id);
    if (idx === -1) return;

    // The snapshots list is sorted newest-first (created_at DESC)
    // The previous snapshot in timeline order is at index idx + 1
    const prev = snapshots[idx + 1];
    if (prev) {
      setDiffFrom(prev);
      setDiffTo(s);
    } else {
      // Diff against itself (displays as all additions)
      setDiffFrom(s);
      setDiffTo(s);
    }
  };

  const handleInitialize = async () => {
    try {
      if (typeof window !== "undefined" && (window as any).go) {
        setLoading(true);
        await InitializeProject();
        setInitialized(true);
        await loadSnapshots();
      }
    } catch (err: any) {
      alert(`Failed to initialize Eko: ${err.message || err}`);
    } finally {
      setLoading(false);
    }
  };

  const handleCreateSnapshot = async () => {
    const msg = window.prompt("Enter snapshot message/description (optional):", "Save via Eko UI");
    if (msg === null) return;

    try {
      if (typeof window !== "undefined" && (window as any).go) {
        await SaveSnapshot(msg);
        alert("Snapshot saved successfully!");
        await loadSnapshots();
      } else {
        alert("Demo mode: Snapshot simulated");
      }
    } catch (err: any) {
      alert(`Failed to save snapshot: ${err.message || err}`);
    }
  };

  const activeProject = {
    id: activeProjectId,
    name: activeProjectName,
    snapshots: snapshots,
  };

  if (loading) {
    return (
      <div style={{ display: "flex", height: "100vh", alignItems: "center", justifyContent: "center", background: "#0f172a", color: "#f8fafc" }}>
        <p>Loading Eko Timeline...</p>
      </div>
    );
  }

  if (!initialized) {
    return (
      <div style={{ display: "flex", height: "100vh", alignItems: "center", justifyContent: "center", background: "#0f172a", color: "#f8fafc", fontFamily: "inherit" }}>
        <div style={{ background: "rgba(30, 41, 59, 0.7)", border: "1px solid rgba(255, 255, 255, 0.1)", borderRadius: "16px", padding: "40px", maxWidth: "480px", textAlign: "center", boxShadow: "0 20px 25px -5px rgba(0, 0, 0, 0.5)", backdropFilter: "blur(8px)" }}>
          <div style={{ fontSize: "48px", marginBottom: "16px", color: "#38bdf8" }}>✦</div>
          <h1 style={{ fontSize: "24px", fontWeight: "bold", marginBottom: "8px" }}>Eko is not initialized</h1>
          <p style={{ color: "#94a3b8", fontSize: "14px", lineHeight: "1.6", marginBottom: "24px" }}>
            The folder <code style={{ background: "#0f172a", padding: "2px 6px", borderRadius: "4px", color: "#38bdf8" }}>{activeProjectName}</code> is not set up with Eko. Initialize it now to start capturing and tracking your snapshots.
          </p>
          <button
            onClick={handleInitialize}
            style={{ width: "100%", padding: "12px", background: "#38bdf8", color: "#0f172a", border: "none", borderRadius: "8px", fontSize: "14px", fontWeight: "bold", cursor: "pointer", transition: "background 0.2s" }}
            onMouseOver={(e) => (e.currentTarget.style.background = "#0ea5e9")}
            onMouseOut={(e) => (e.currentTarget.style.background = "#38bdf8")}
          >
            Initialize Eko
          </button>
        </div>
      </div>
    );
  }

  return (
    <div className="app">
      <Sidebar
        projects={[activeProject]}
        activeId={activeProjectId}
        onSelect={() => {}}
      />

      <Timeline
        projectName={activeProjectName}
        snapshots={snapshots}
        selectedId={selectedSnapshot?.id ?? null}
        onSelect={setSelectedSnapshot}
        onDiff={handleDiff}
        onRestore={handleRestore}
        onCreateSnapshot={handleCreateSnapshot}
      />

      <DetailPanel
        snapshot={selectedSnapshot}
        onRestore={handleRestore}
        onDiff={handleDiff}
      />

      {diffFrom && diffTo && (
        <DiffViewer
          fromSnapshot={diffFrom}
          toSnapshot={diffTo}
          onClose={() => {
            setDiffFrom(null);
            setDiffTo(null);
          }}
        />
      )}
    </div>
  );
}
