"use client";
import { useState, useEffect } from "react";
import Sidebar from "@/components/Sidebar";
import Timeline from "@/components/Timeline";
import DetailPanel from "@/components/DetailPanel";
import DiffViewer from "@/components/DiffViewer";
import { PROJECTS, type Snapshot } from "@/lib/data";

// Wails bindings (auto-generated by Wails CLI at build/dev time)
import { ListSnapshots, RestoreSnapshot } from "@/lib/wailsjs/go/main/WailsApp";

export default function Home() {
  const [snapshots, setSnapshots] = useState<Snapshot[]>([]);
  const [selectedSnapshot, setSelectedSnapshot] = useState<Snapshot | null>(null);
  const [loading, setLoading] = useState(true);
  const [diffFrom, setDiffFrom] = useState<Snapshot | null>(null);
  const [diffTo, setDiffTo] = useState<Snapshot | null>(null);

  const activeProjectId = "eko";
  const activeProjectName = "eko";

  const loadSnapshots = async () => {
    try {
      if (typeof window !== "undefined" && (window as any).go) {
        const data = await ListSnapshots();
        setSnapshots(data);
        if (data.length > 0) {
          setSelectedSnapshot(data[0]);
        }
      } else {
        // Fallback to mock data in browser dev mode
        const mockSnapshots = PROJECTS[0].snapshots;
        setSnapshots(mockSnapshots);
        if (mockSnapshots.length > 0) {
          setSelectedSnapshot(mockSnapshots[0]);
        }
      }
    } catch (err) {
      console.error("Failed to load snapshots:", err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    loadSnapshots();
  }, []);

  const handleRestore = async (s: Snapshot) => {
    const confirm = window.confirm(`Restore snapshot #${s.id} — "${s.prompt}"?\nThis will revert files in your project directory.`);
    if (!confirm) return;

    try {
      if (typeof window !== "undefined" && (window as any).go) {
        await RestoreSnapshot(s.id);
        alert(`Snapshot #${s.id} restored successfully.`);
      } else {
        alert(`Demo mode: Restore simulated for snapshot #${s.id}`);
      }
    } catch (err: any) {
      alert(`Failed to restore snapshot: ${err.message || err}`);
    }
  };

  const handleDiff = (s: Snapshot) => {
    const idx = snapshots.findIndex((snap) => snap.id === s.id);
    if (idx === -1) return;

    // The snapshots list is sorted newest-first (created_at DESC)
    // The previous snapshot in timeline order is at index idx + 1
    const prev = snapshots[idx + 1];
    if (prev) {
      setDiffFrom(prev);
      setDiffTo(s);
    } else {
      // Diff against itself (displays as all additions)
      setDiffFrom(s);
      setDiffTo(s);
    }
  };

  const activeProject = {
    id: activeProjectId,
    name: activeProjectName,
    snapshots: snapshots,
  };

  if (loading) {
    return (
      <div style={{ display: "flex", height: "100vh", alignItems: "center", justifyContent: "center", background: "#0f172a", color: "#f8fafc" }}>
        <p>Loading Eko Timeline...</p>
      </div>
    );
  }

  return (
    <div className="app">
      <Sidebar
        projects={[activeProject]}
        activeId={activeProjectId}
        onSelect={() => {}}
      />

      <Timeline
        projectName={activeProjectName}
        snapshots={snapshots}
        selectedId={selectedSnapshot?.id ?? null}
        onSelect={setSelectedSnapshot}
        onDiff={handleDiff}
        onRestore={handleRestore}
      />

      <DetailPanel
        snapshot={selectedSnapshot}
        onRestore={handleRestore}
        onDiff={handleDiff}
      />

      {diffFrom && diffTo && (
        <DiffViewer
          fromSnapshot={diffFrom}
          toSnapshot={diffTo}
          onClose={() => {
            setDiffFrom(null);
            setDiffTo(null);
          }}
        />
      )}
    </div>
  );
}
