// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DiffSnapshots(arg1, arg2) {
  return window['go']['main']['WailsApp']['DiffSnapshots'](arg1, arg2);
}

export function GetProjectName() {
  return window['go']['main']['WailsApp']['GetProjectName']();
}

export function GetSnapshot(arg1) {
  return window['go']['main']['WailsApp']['GetSnapshot'](arg1);
}

export function IsInitialized() {
  return window['go']['main']['WailsApp']['IsInitialized']();
}

export function InitializeProject() {
  return window['go']['main']['WailsApp']['InitializeProject']();
}

export function ListSnapshots() {
  return window['go']['main']['WailsApp']['ListSnapshots']();
}

export function RestoreSnapshot(arg1) {
  return window['go']['main']['WailsApp']['RestoreSnapshot'](arg1);
}

export function SaveSnapshot(arg1) {
  return window['go']['main']['WailsApp']['SaveSnapshot'](arg1);
}
