// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {api} from '../models';
import {main} from '../models';

export function DiffSnapshots(arg1:string,arg2:string):Promise<Array<api.DiffFile>>;

export function GetProjectName():Promise<string>;

export function GetSnapshot(arg1:string):Promise<api.SnapshotRecord>;

export function IsInitialized():Promise<boolean>;

export function InitializeProject():Promise<string>;

export function ListSnapshots():Promise<Array<main.FrontendSnapshot>>;

export function RestoreSnapshot(arg1:string):Promise<Record<string, string>>;

export function SaveSnapshot(arg1:string):Promise<string>;
