name: Bug Report
description: File a bug report to help us improve Eko
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Run 'eko init'
        2. Run 'eko save'
        3. ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Eko Version
      description: What version of Eko are you using? (Run 'eko version' if available)
  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here (OS, Go version, etc.)
